project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Community"
  site-url: "https://community.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/community"
  page-navigation: true
  navbar:
    title: false
    logo: _extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-community.svg
    logo-alt: "Seedcase Community logo: Main page"
    pinned: true
    search: true
    left:
      - guides/index.qmd
      - posts/index.qmd
      - learn/index.qmd
    tools:
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Seedcase Project home page"
      - icon: github
        href: "https://github.com/seedcase-project/community"
        aria-label: "GitHub icon: Source code"
  sidebar:
    - id: guides
      pinned: true
      style: "floating"
      contents:
        - auto: guides

format:
  seedcase-theme-html:
    theme:
      - brand
    include-before-body:
      - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
