project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Community"
  site-url: "https://community.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/community"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: LICENSE.md
      - text: "Code of Conduct"
        href: "https://github.com/seedcase-project/.github/blob/main/CODE_OF_CONDUCT.md"
  page-navigation: true
  navbar:
    title: false
    logo: _extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-community.svg
    logo-alt: "Seedcase Community logo"
    pinned: true
    search: true
    left:
      - roadmap.qmd
      - guides/index.qmd
      - outreach/index.qmd
      - posts/index.qmd
    tools:
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: Home
      - icon: github
        href: "https://github.com/seedcase-project/community"
        aria-label: GitHub
  sidebar:
    - id: guides
      pinned: true
      style: "floating"
      contents:
        - auto: guides
    - id: outreach
      contents:
        - outreach/index.qmd
        - text: "Events"
          auto: outreach/**/index.qmd
    - id: posts
      contents:
        - auto: posts

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
