---
title: Roadmap
---

{{< include /includes/_wip.qmd >}}

This is a very high level roadmap and "wishlist" for products we aim or
want to create and develop in the Seedcase Project. We do not include
timelines or estimates for completion in this document (see note below).
We have a more detailed and regularly updated roadmap that has some
general timelines available on our [Long-term Planning GitHub
Board](https://github.com/orgs/seedcase-project/projects/22/views/1).

::: callout-important
Estimating the timeline, especially for software projects, is extremely
difficult, as it is dependent on multiple factors that often can't be
predicted or anticipated. For instance, for software products, we could
encounter difficult bugs in the code or in revising the implementation
based on changing technical needs and resources. For documentation
projects, at least the ones that we will be and are working on in the
Seedcase Project, they often frequently evolve as we learn, apply, test,
and refine how we work and what we do. For these reasons, and from our
experiences on timelines regularly needing to be updated, we avoid
giving specific timelines in this document. Regular updates to the
estimated timeline of *some* of our projects are found in the
[roadmap](https://github.com/orgs/seedcase-project/projects/22/views/1).
:::

## Product wishlist

This is a non-exhaustive list of products or outputs that we believe
fill multiple strong needs within the research community, especially in
order to remain relevant and competitive in the modern research
landscape. We believe that, while we can't complete all of them given
our current timelines and resources, we have the capability, expertise,
motivation, and passion to complete these ones and ultimately, we
believe, substantially improve how research will be done in the future.

They are split into three main categories: software-related, technical
documentation, and events. Technical documentation encompasses more than
just usage guides or manuals for software, but also includes courses,
opinion pieces, and outreach materials.

Products are listed in the order that we would like to work on and aim
to complete. Beside each product is a status, which is one of the
following:

-   {{< var status.done >}}: Products we have completed a minimally
    viable product (MVP) of. While all are products are never truly
    "done", the "done" status simply indicates that the product is now
    in a usable state, but that we will continue improving and working
    on.
-   {{< var status.wip >}}: Products we are currently working on.
-   {{< var status.planned >}}: Products we plan on worked on and aim to
    complete within the funding period (end of 2027).
-   {{< var status.potential >}}: Products we are very interested in
    working on, but given the time and resource, may likely not get to
    within the funding period (end of 2027).

### Software-related

Because of the evolving nature of developing software, software products
are rarely "complete" as they continue to be improved on and updated.
The product reaches MVP and done status when we have created it's first
release on an official software archive (like PyPI for Python packages).
After the first release of a minimum viable product and if it gets
sufficient use, it would continue to be tested and refined based on user
feedback, identified bugs, and additional features.

Some of these products are not strictly software, but can be used within
a software environment, can be integrate into other workflows, or are
used to support research software and data engineering.

| Status | Software-related product |
|----------------------------------------------------|--------------------|
| {{< var status.wip >}} | [`seedcase-project/seedcase-sprout`](https://github.com/seedcase-project/seedcase-sprout): Upload your research data to formally structure it for better, more reliable, and easier research. |
| {{< var status.wip >}} | [`seedcase-project/seedcase-theme`](https://github.com/seedcase-project/seedcase-theme): Template repository for website projects with a Seedcase-specific Quarto extension for aesthetics, helper commands, and infrastructural files. |
| {{< var status.wip >}} | [`seedcase-project/template-python-project`](https://github.com/seedcase-project/template-python-project): A template repository to use when making a Python project for Seedcase. |
| {{< var status.wip >}} | [`seedcase-project/spaid`](https://github.com/seedcase-project/spaid): Seedcase Project aid, a toolkit for developing Seedcase projects. |
| {{< var status.planned >}} | `seedcase-flower`: Cataloging and browsing metadata on data in a data package. |
| {{< var status.planned >}} | `seedcase-propagate`: Submitting request for accessing specific data from a data package. |
| {{< var status.planned >}} | `seedcase-garden`: Tend to and track projects using data from a data package. |
| {{< var status.planned >}} | `seedcase-sprout-extensions`: Extensions to Seedcase Sprout for common data processing or enriching tasks. |

: "Wishlist" of software-related products we currently working on, will
work on, or hope to work on.

### Technical documentation

Following the [diátaxis](https://diataxis.fr/) method to structuring
documentation, they are split up into four documentation types: learning
(tutorials or courses), goals (how-to guides), information (reference
manuals), and understanding (explanations, opinions, and maybe
outreach). These technical documentation products reach MVP and done
status when they either are first:

-   Uploaded to an archive like Zenodo (to generate a DOI).
-   Taught to participants in a course setting.
-   Uploaded to a software archive (like PyPI) if they are within a
    software product's repository and are executable (the code within
    runs).

::: panel-tabset
#### Learning

This would include courses, brief tutorials, and learning shorts. These
would be developed as [open educational
resources](https://en.wikipedia.org/wiki/Open_educational_resources).

| Status | Learning resource |
|-----------------------------------------------|------------------------|
| {{< var status.wip >}} | [`rostools/git4cats`](https://github.com/rostools/git4cats): :cat: Git for Collaborative Teams: An introductory course on using Git and GitHub for team-based collaborative workflows and practices |
| {{< var status.planned >}} | [`rostools/r-pkg-intro`](https://github.com/rostools/r-pkg-intro): Build research software using R as a solo developer in research environments. |
| {{< var status.potential >}} | Course: Iterative project management and development for effective collaboration and work. |
| {{< var status.potential >}} | Course: Introduction to building research software using Python as a solo developer in research environments. |
| {{< var status.potential >}} | Course: Building research software in a team. |

: "Wishlist" of learning-type documentation products we currently
working on, will work on, or hope to work on.

#### Goals

This includes how-to guides, usage guides, and manuals.

| Status | Guides or manuals |
|-----------------------------------------------|------------------------|
| {{< var status.wip >}} | [`sprout.seedcase-project.org`](https://sprout.seedcase-project.org/docs/guide) usage guide: Using and interacting with `seedcase-sprout`. |
| {{< var status.planned >}} | Flower usage guide: Using and interacting with `seedcase-flower`. |
| {{< var status.planned >}} | Propagate usage guide: Using and interacting with `seedcase-propagate`. |
| {{< var status.planned >}} | Garden usage guide: Using and interacting with `seedcase-garden`. |
| {{< var status.planned >}} | Sprout extensions usage guide: Installing or creating extensions for `seedcase-sprout`. |
| {{< var status.planned >}} | Installing and setting up Seedcase software on server environments. |
| {{< var status.planned >}} | Using Seedcase to create and manage data packages. |
| {{< var status.planned >}} | A guided walkthrough: Team-based collaborative practices and workflows in a research environment. |
| {{< var status.planned >}} | A guided walkthrough: Iterative and incremental project development and management in a research environment. |
| {{< var status.planned >}} | Using DocOps workflows and infrastructure to reduce time between writing and dissemination. |
| {{< var status.planned >}} | Building DataOps pipelines and infrastructure for improving research data quality and reduce time from collection to analysis. |
| {{< var status.planned >}} | Improving the research software development lifecycle by integrating DevOps practices. |
| {{< var status.potential >}} | Integrating research operations in organizations to improve quality and speed up research. |

: "Wishlist" of goal-type documentation products we currently working
on, will work on, or hope to work on.

#### Information

This includes reference manuals, API documentation, and technical
specifications, as well as documentation for how we work together,
decisions made, or any community contributing guidelines we have.

| Status | Information resource |
|-----------------------------------------------|------------------------|
| {{< var status.wip >}} | [`seedcase-project/decisions`](https://github.com/seedcase-project/decisions): Archival records on the decisions made for tools or processes we use in the Seedcase Project. |
| {{< var status.wip >}} | [`seedcase-project/design`](https://github.com/seedcase-project/design): Overall architectural design documentation for Seedcase software. |
| {{< var status.wip >}} | [`seedcase-project/team`](https://github.com/seedcase-project/team): Documentation specific to the Seedcase team, like onboarding, common configuration files, and meeting agendas and minutes. |
| {{< var status.wip >}} | [`seedcase-project/community`](https://github.com/seedcase-project/community): Content for community building, outreach, and contributing guidelines for the Seedcase Project. |
| {{< var status.wip >}} | [`seedcase-project/seedcase-website`](https://github.com/seedcase-project/seedcase-website): Main website for the Seedcase Project. |
| {{< var status.wip >}} | [`seedcase-project/data`](https://github.com/seedcase-project/data): Practical examples of projects using Seedcase software. All data is either fake, synthetically generated, or completely open. |

: "Wishlist" of informational-type documentation products we currently
working on, will work on, or hope to work on.

### Explanations

This includes opinion pieces, explanations, theoretical or
though-provoking pieces, and outreach materials.

| Status | Deliverable |
|-----------------------------------------------|------------------------|
| {{< var status.wip >}} | Knowledge sharing via the [Community](https://community.seedcase-project.org/) website: Knowledge and skills learned from attending conferences and workshops in research software and data engineering or operational management |
| {{< var status.potential >}} | Opinion: Workflows and digital infrastructure for building software in a team-based research environment |
| {{< var status.potential >}} | Challenges and barriers in research for effective software development and data engineering. |
| {{< var status.potential >}} | Research data engineering: What is it and why is it vital for modern research? |
| {{< var status.potential >}} | Researchers don't know how to effectively work together: Current challenges and potential solutions. |
| {{< var status.potential >}} | Research institutions and funding agencies are not yet designed to support effective and robust, but vital, research software development. |

: "Wishlist" of explanation-type documentation products we currently
working on, will work on, or hope to work on.
:::

### Outreach and events

These are activities that would involve engaging with the research
community, mainly through in-person seminars, symposiums, or other
events.

::: callout-note
Given the expertise and resources needed for these types of "products"
(e.g. hosting and coordinating people), we will likely not be able to
work on these types of activities in the near future. However, we
believe that they are important to bring greater awareness to the
research community about the various topics we work on and advocate for.
:::

| Status | Deliverable |
|-----------------------------------------------|------------------------|
| {{< var status.potential >}} | Seminar series: Unmet needs for research data engineering and current challenges in implementation |
| {{< var status.potential >}} | Symposium: Current state of data engineering in research environment |

: "Wishlist" of outreach event "products" we currently working on, will
work on, or hope to work on.

## Collaborations and users

Once we have a minimum viable product for any of the software
deliverables, we aim to test and deploy them in real-world projects. We
have several potential projects lined up for this:

-   [DP-Next](https://dp-next.github.io/)
-   [ADDITION](https://addition.au.dk/)
-   [Health in Central
    Region](https://www.stenoaarhus.dk/tvarsektoriel-forskning/helbred-i-midt/)
-   [DARTER](https://steno-aarhus.github.io/darter-project/)
    (register-based research project at Steno)
-   [DD2](https://dd2.dk/)


