---
title: "The Seedcase Project: A data engineering framework and tools for building and managing open and FAIR research data"
author:
  - name: Kristiane Beicher
    orcid: "https://orcid.org/0000-0001-7556-9566"
  - name: Signe K. Brødbæk
    orcid: "https://orcid.org/0009-0000-2208-7088"
  - name: Luke W. Johnston
    orcid: "https://orcid.org/0000-0003-4169-2616"
  - name: Joel Ostblom
    orcid: "https://orcid.org/0000-0003-0051-3239"
  - name: Marton Vago
    orcid: "https://orcid.org/0009-0007-4628-655X"
# Prevent it from entering the post listing page.
exclude-from-listing: true
---

::: content-hidden
From: https://ois-research-conference.org/ois-research-conference-2026/

Submission word limit: 250-500.

Words in document: 497

Submitting to track 1: Open and collaborative approaches along the
entire scientific research process, including opportunities, challenges,
and contingency factors. Possible topics include but are not limited to:

-   Open data/material sharing/re-use
-   Platforms facilitating open and collaborative approaches to
    scientific research
:::

FAIR and open practices are beneficial for science as they encourage
reproducible, transparent, and shareable data practices.
While individual researchers sometimes are capable of implementing FAIR
and open practices on their own, the availability of software and data
engineering resources and tools greatly facilitates the adoption of
these practices.
Unfortunately, there is a lack of systemic structures to incentivise
researchers, organizations, and funding agencies to appreciate the
importance of software and data engineering in research contexts and to
dedicate sufficient resources to implementing them in practice.
A major consequence from this incentive misalignment is that researchers
trying to adhere to FAIR and open practices face organizational and
technical challenges with managing, sharing, building, and using
research data, which in turn hampers scientific progress.

In the Seedcase Project (\<seedcase-project.org\>), we aim to resolve
part of the aforementioned issues by developing a framework that
facilitates the creation and management of FAIR research data. To reach
this goal, we are developing a set of interoperable and modular tools that together
constitute a modern, organized, and robust framework.
The tools we've published so far include:

-   Sprout (\<sprout.seedcase-project.org\>): A Python package that
    helps create and manage a standardised and organised
    structure for storing and describing research data as a Data Package. Using modern
    data engineering and management practices, Sprout promotes
    research data that are well designed, discoverable,
    well documented, and ultimately (re)usable for later analyses.
    This package is built around the Data Package standard
    (\<datapackage.org\>).
-   `check-datapackage` (\<check-datapackage.seedcase-project.org\>):
    A Python package that checks your Data Package's metadata against
    the Data Package standard to ensure that a Data Package's metadata is compliant
    with the standard.
-   Template Data Package
    (\<template-data-package.seedcase-project.org\>): This is a template
    for creating a new Data Package following the Seedcase structure
    with the necessary files and configurations in place.

Tools that are planned or in early development:

-   Flower (\<flower.seedcase-project.org\>): A Python package and
    command-line tool to generate and display your `datapackage.json`
    file in a human-friendly way. In early development.
-   Propagate: A planned tool to make it easier to submit and process
    reproducible requests for a subset of data from a larger Data
    Package through a machine-readable set of instructions.
-   Garden: A planned tool to manage and track research projects using a
    Data Package

In addition to publishing data engineering tools, we also publish our
internal developer tools, documentation, and guides to effective
collaborative practices. Through these publications, we contribute to
our ultimate goal of helping researchers do "better science in less
time", not only in an academic settings in Denmark but also in industry
and across the globe. Our progress towards this goal can be found in our
roadmap at \<seedcase-project.org/roadmap/\> which lists all of our
products and their development status.

This project is funded by a Novo Nordisk Foundation grant (number
NNF21OC0069462).

::: content-hidden
## Keywords (max 6)

data engineering FAIR data data management data infrastructure metadata
management metadata standards
:::
